{
 "title": "FVE Statistics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "PRICE_PER_KW",
    "label": "Price per kW",
    "query": "SELECT\nVT_price AS \"high tarif\"\nFROM elektro\nORDER BY DATE(timestamp) DESC LIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Generated power today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"e_day\"\n  )"
    }
   ]
  },
  {
   "title": "Saved today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kč" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"e_day\")\n  |> map(fn: (r) => ({ r with _value: r._value * $PRICE_PER_KW }))"
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"battery_mode\"\n  )"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"battery_temperature\")"
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Total Power Generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"e_total\"\n  )"
    }
   ]
  },
  {
   "title": "Saved total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kč" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"e_total\")\n  |> map(fn: (r) => ({ r with _value: r._value * $PRICE_PER_KW }))"
    }
   ]
  },
  {
   "title": "Battery state of Charge (SOC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"battery_soc\")\n"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"vbattery1\")"
    }
   ]
  },
  {
   "title": "Inverter AC Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Battery Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"battery_error_h\" or r._field == \"battery_error_l\")"
    }
   ]
  },
  {
   "title": "Inverter AC Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"backup_f1\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM elektro\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Current Power Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._field == \"load_ptotal\")"
    }
   ]
  },
  {
   "title": "Power from Grid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"active_power_total\"\n  )"
    }
   ]
  },
  {
   "title": "Battery Power Status",
   "type": "stat",
   "description": "Negative value = Charging",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._field == \"pbattery1\")"
    }
   ]
  },
  {
   "title": "Solar power generating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"ppv\"\n  )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"active_power_total\"\n  )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"battery_mode\"\n  )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._field == \"load_p1\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Load L1 (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._field == \"load_p2\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Load L2 (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._field == \"load_p3\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Load L3 (W)\" }))"
    }
   ]
  },
  {
   "title": "Power from Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"active_power1\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Active Power L1 (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"active_power2\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Active Power L2 (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"active_power3\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Active Power L3 (W)\" }))"
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"pbattery1\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Battery Total (W)\" }))"
    }
   ]
  },
  {
   "title": "Solar PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"ppv\"\n  )"
    }
   ]
  },
  {
   "title": "Power usage last 30d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"e_load_day\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Sun Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "sun_altitude"
    }
   ]
  },
  {
   "title": "Power generation last 30d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"FVE_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"e_day\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "All-in-one",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>r._field == \"load_ptotal\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Load (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>r._field == \"active_power_total\" )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Meter - Grid (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>r._field == \"pbattery1\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Battery (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"ppv\" )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"PV -Generating power (W)\" }))"
    },
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"battery_soc\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Batter State of Charge (SOC) (%)\" }))\r\n"
    }
   ]
  }
 ]
}