apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: <token> 
    jsonData:
      version: Flux
      organization: <org>
      defaultBucket: FVE
      tlsSkipVerify: true


  - name: sunandmoon
    type: fetzerch-sunandmoon-datasource
    jsonData:
      latitude: 48.0
      longitude: 10.0
    editable: true
